apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/instance: chatbot-m1742471791499
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: chatbot-m1742471791499
  name: chatbot-m1742471791499
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi
